version: 2
jobs:
  build:
    docker:
    - image: asciidoctor/docker-asciidoctor
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: build adoc
        command: asciidoctor -D `pwd`/output `pwd`/index.adoc
    - persist_to_workspace:
        root: ~/repo
        paths:
        - output/*

  upload:
    docker:
    - image: garland/aws-cli-docker:1.15.47
    working_directory: ~/repo
    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - run:
        name: upload adoc
        command: ./publish_to_S3.sh

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
    - upload:
        requires:
        - build
        filters:
          branches:
            only:
            - master
