[[api-operation]]
= API Operation

[#192]
== {MUST} Publish OpenAPI Specification

All service applications must publish OpenAPI specifications of their external
APIs.

An API is published by uploading its built **SwaggerUI** docs built from its
**OpenAPI Specification** into Infinitec's internal documentation S3 folder,
preferrably via automated CI job. The directory structure should be
`/apis/{REPOSITORY_NAME}/index.html`. A link to the published documentation
must be present at the repository's README file. It is important to remember
that the publishing process is separated from the drafting discussion, which
can happen via Github pull requests with temporary build artifacts, or via
whiteboarding.

Background: In our dynamic and complex service infrastructure, it is important
to provide API client developers a central place with online access to the API
specifications of all running applications.

[#193]
== {SHOULD} Monitor API Usage

Owners of APIs used in production should monitor API service to get
information about its using clients. This information, for instance, is
useful to identify potential review partner for API changes.

Hint: A preferred way of client detection implementation is by logging
of the client-id retrieved from the OAuth token.

