[[common-data-types]]
= Common Data Types

Definitions of data objects that are good candidates for wider usage:

[#173]
== {SHOULD} Use a Common Money Object

Use the following common money structure:

[source,yaml]
----
Money:
  type: object
  properties:
    amount:
      type: number
      description: Amount expressed as a decimal number of major currency units
      format: decimal
      example: 99.95
    currency:
      type: string
      description: 3 letter currency code as defined by ISO-4217
      format: iso-4217
      example: EUR
  required:
    - amount
    - currency
----

The decimal values for "amount" describe unit and subunit of the
currency in a single value, where the digits before the decimal point
are for the major unit and the digits after the decimal point are for
the minor unit. Note that some business cases (e.g. transactions in
Bitcoin) call for a higher precision, so applications must be prepared
to accept values with unlimited precision, unless explicitly stated
otherwise in the API specification. Examples for correct representations
(in EUR):

* `42.20` or `42.2` = 42 Euros, 20 Cent
* `0.23` = 23 Cent
* `42.0` or `42` = 42 Euros
* `1024.42` = 1024 Euros, 42 Cent
* `1024.4225` = 1024 Euros, 42.25 Cent

Make sure that you don’t convert the "amount" field to `float` /
`double` types when implementing this interface in a specific language
or when doing calculations. Otherwise, you might lose precision.
Instead, use exact formats like Java’s
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html[`BigDecimal`].
See http://stackoverflow.com/a/3730040/342852[Stack Overflow] for more
info.

Some JSON parsers (NodeJS’s, for example) convert numbers to floats by
default. After discussing the pros and cons we’ve decided on "decimal" as our amount format. It
is not a standard OpenAPI format, but should help us to avoid parsing numbers
as float / doubles.

[#174]
== {MUST} Use common field names and semantics

There exist a variety of field types that are required in multiple
places. To achieve consistency across all API implementations, you must
use common field names and semantics whenever applicable.

[[generic-fields]]
=== Generic Fields

There are some data fields that come up again and again in API data:

* `id`: the identity of the object. If used, IDs must be opaque strings and
not numbers. IDs are unique within some documented context, are stable
and don't change for a given object once assigned, and are never
recycled cross entities.
* `...Id`: an attribute within one object holding the identifier of
another object must use a name that corresponds to the type of the
referenced object or the relationship to the referenced object followed
by `Id` (e.g. `businessId` not `businessNumber`; `parentNodeId` for
the reference to a parent node from a child node, even if both have the
type `Node`)
* `createdAt`: date-time at which the object was created.
* `updatedAt`: date-time at which the object was updated.
* `...At`: any date-time property of the object, both past and future, e.g.
`disabledAt`, `expiresAt`.
* `...Date`: any date property of the object, e.g. `reconciliationDate`.
* `...Time`: any time property of the object, e.g. `deliveryTime`.
* `status`: status of the object in the system. If used, the type of this field
must be a string, carrying values of enumeration or <<112, extensible
enumeration>>. Consider using `status` property instead of boolean flags
representing status (e.g. `isLocked`, `isFinished`), as the former is more
extensible and allows easier documentation of all allowed statuses, transitions
& their consequences.
* `type`: the kind of thing this object is. If used, the type of this
field must be a string, carrying values of enumeration or extensible
enumeration. Types allow runtime information on the entity provided that
otherwise requires examining the Open API file.
* `etag`: the <<182, ETag>> of an <<158, embedded sub-resource>>. It may be
  used to carry the {ETag} for subsequent {PUT}/{PATCH} calls (see
  <<etag-in-result-entities>>).

Example JSON Schema:

[source,yaml]
----
treeNode:
  type: object
  properties: 
    id:
      description: the identifier of this node
      type: string
    createdAt:
      description: date-time at which this node was created
      type: string
      format: 'date-time'
    updatedAt:
      description: date-time at which this node was last updated
      type: string
      format: 'date-time'
    expiresAt:
      description: date-time at which this node will expire
      type: string
      format: 'date-time'
    status:
      type: string
      enum: [ 'ACTIVE', 'EXPIRED' ]
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parentNodeId:
      description: the identifier of the parent node of this node
      type: string
  example:
    id: '123435'
    createdAt: '2017-04-12T23:20:50.52Z'
    updatedAt: '2017-04-12T23:20:50.52Z'
    expiresAt: '2222-04-12T23:20:50.52Z'
    status: 'ACTIVE'
    type: 'LEAF'
    parentNodeId: '534321'
----

These properties are not always strictly necessary, but making them
idiomatic allows API client developers to build up a common
understanding of Infinitec's resources. There is very little utility for
API consumers in having different names or value types for these fields
across APIs.
