[[common-data-types]]
= Common Data Types

Definitions of data objects that are good candidates for wider usage:

[#173]
== {MUST} Use a Common Money Object

Use the following common money structure:

[source,yaml]
----
Money:
  type: object
  properties:
    value:
      type: integer
      description: |
        Amount in the smallest indivisible unit of the currency
        (Cents for Euro, for example)
      format: int64
      example: 9995
    currency:
      type: string
      description: 3 letter currency code as defined by ISO-4217
      format: iso-4217
      example: EUR
  required:
    - value
    - currency
----

Examples for correct representations:

* `{"value": 4223, "currency": "EUR"}` = 42 euros, 23 cents
* `{"value": 4200, "currency": "EUR"}` = 42 euros
* `{"value": 23, "currency": "EUR"}` = 23 cents
* `{"value": 4223, "currency": "JPY"}` = 4223 Japanese yens
* `{"value": 4223, "currency": "KWD"}` = 4 Kuwaiti dinars 223 fils

[#174]
== {MUST} Use common field names and semantics

There exist a variety of field types that are required in multiple
places. To achieve consistency across all API implementations, you must
use common field names and semantics whenever applicable.

[[generic-fields]]
=== Generic Fields

There are some data fields that come up again and again in API data:

* `id`: the identity of the object. If used, IDs must be opaque strings and
not numbers. IDs are unique within some documented context, are stable
and don't change for a given object once assigned, and are never
recycled cross entities.
* `...Id`: an attribute within one object holding the identifier of
another object must use a name that corresponds to the type of the
referenced object or the relationship to the referenced object followed
by `Id` (e.g. `businessId` not `businessNumber`; `parentNodeId` for
the reference to a parent node from a child node, even if both have the
type `Node`)
* `createdAt`: date-time at which the object was created.
* `updatedAt`: date-time at which the object was updated.
* `...At`: any date-time property of the object, both past and future, e.g.
`disabledAt`, `expiresAt`.
* `...Date`: any date property of the object, e.g. `reconciliationDate`.
* `...Time`: any time property of the object, e.g. `deliveryTime`.
* `status`: status of the object in the system. If used, the type of this field
must be a string, carrying values of enumeration or <<112, extensible
enumeration>>. Consider using `status` property instead of boolean flags
representing status (e.g. `isLocked`, `isFinished`), as the former is more
extensible and allows easier documentation of all allowed statuses, transitions
& their consequences.
* `type`: the kind of thing this object is. If used, the type of this
field must be a string, carrying values of enumeration or extensible
enumeration. Types allow runtime information on the entity provided that
otherwise requires examining the Open API file.
* `etag`: the <<182, ETag>> of an <<158, embedded sub-resource>>. It may be
  used to carry the {ETag} for subsequent {PUT}/{PATCH} calls (see
  <<etag-in-result-entities>>).

Example JSON Schema:

[source,yaml]
----
treeNode:
  type: object
  properties:
    id:
      description: the identifier of this node
      type: string
    createdAt:
      description: date-time at which this node was created
      type: string
      format: 'date-time'
    updatedAt:
      description: date-time at which this node was last updated
      type: string
      format: 'date-time'
    expiresAt:
      description: date-time at which this node will expire
      type: string
      format: 'date-time'
    status:
      type: string
      enum: [ 'ACTIVE', 'EXPIRED' ]
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parentNodeId:
      description: the identifier of the parent node of this node
      type: string
  example:
    id: '123435'
    createdAt: '2017-04-12T23:20:50.52Z'
    updatedAt: '2017-04-12T23:20:50.52Z'
    expiresAt: '2222-04-12T23:20:50.52Z'
    status: 'ACTIVE'
    type: 'LEAF'
    parentNodeId: '534321'
----

These properties are not always strictly necessary, but making them
idiomatic allows API client developers to build up a common
understanding of Infinitec's resources. There is very little utility for
API consumers in having different names or value types for these fields
across APIs.

[[listing-fields]]
=== Listing Fields

Response properties of listing endpoints should follow the naming and semantics
defined below. This makes the general listing response the same regardless of
specific listing (modulo elements in the listing).

* `items`: name of property holding elements of returned listing.
