[[hypermedia]]
= Hypermedia

[#162]
== {MUST} Use REST Maturity Level 2

We strive for a good implementation of
http://martinfowler.com/articles/richardsonMaturityModel.html#level2[REST
Maturity Level 2] as it enables us to build resource-oriented APIs that
make full use of HTTP verbs and status codes. You can see this expressed
by many rules throughout these guidelines, e.g.:

* <<138>>
* <<141>>
* <<148>>
* <<150>>

Although this is not HATEOAS, it should not prevent you from designing
proper link relationships in your APIs as stated in rules below.

[#217]
== {MUST} Use full, absolute URI

Links to other resource must always use full, absolute URI.

*Motivation*: Exposing any form of relative URI (no matter if the relative
URI uses an absolute or relative path) introduces avoidable client side
complexity. It also requires clarity on the base URI, which might not be given
when using features like embedding subresources. The primary advantage
of non-absolute URI is reduction of the payload size, which is better
achievable by following the recommendation to use <<156,gzip compression>>

[#166]
== {MUST} Not Use Link Headers with JSON entities

We don't allow the use of the {RFC-5988}#section-5[`Link` Header defined by
RFC 5988] in conjunction with JSON media types. We prefer links directly
embedded in JSON payloads to the uncommon link header syntax.
