[[json-guidelines]]
= JSON Guidelines

These guidelines provides recommendations for defining JSON data.
JSON here refers to {RFC-7159}[RFC 7159] (which updates {RFC-4627}[RFC 4627]),
the "application/json" media type and custom JSON media types defined for APIs.
The guidelines clarifies some specific cases to allow JSON data to have
an idiomatic form across teams and services.

The first some of the following guidelines are about property names, the later
ones about values.


[#118]
== {MUST} Property names must be ASCII camelCase (and never snake_case): `^[a-z][a-zA-Z0-9]*$`

Property names are restricted to ASCII strings. The first
character must be a letter, and subsequent characters can be a letter or a
number.

(It is recommended to use `_` at the start of property names only for keywords like `_links`.)

Rationale: No established industry standard exists, but it’s essential to establish
a consistent look and feel such that JSON looks as if it came from the same hand.


[#216]
== {SHOULD} Define Maps Using `additionalProperties`

A "map" here is a mapping from string keys to some other type.
In JSON this is represented as an object, the key-value pairs being represented
by property names and property values.
In OpenAPI schema (as well as in JSON schema) they should be represented using
additionalProperties with a schema defining the value type. Such an object should normally
have no other defined properties.

The map keys don't count as property names in the sense of <<118,rule 118>>, and can
follow whatever format is natural for their domain. Please document this in the description
of the map object's schema.

Here is an example for such a map definition (the `translations` property):

```yaml
components:
  schemas:
    Message:
      description:
        A message together with translations in several languages.
      type: object
      properties:
        message_key:
          type: string
          description: The message key.
        translations:
          description:
            The translations of this message into several languages.
            The keys are [IETF BCP-47 language tags](https://tools.ietf.org/html/bcp47).
          type: object
          additionalProperties:
            type: string
            description:
              the translation of this message into the language identified by the key.
```

An actual JSON object described by this might then look like this:
```json
{ "message_key": "color",
  "translations": {
    "de": "Farbe",
    "en-US": "color",
    "en-GB": "colour",
    "eo": "koloro",
    "nl": "kleur"
  }
}
```


[#120]
== {MUST} Array names must be pluralized

To indicate they contain multiple values pluralize array
names. This implies that object names must in turn be singular.


[#122]
== {MUST} Boolean property values must not be null

Schema based JSON properties that are by design booleans must not be
presented as nulls. A boolean is essentially a closed enumeration of two
values, true and false. If the content has a meaningful null value,
strongly prefer to replace the boolean with enumeration of named values
or statuses - for example accepted_terms_and_conditions with true or
false can be replaced with terms_and_conditions with values yes, no and
unknown.


[#123]
== {SHOULD} Null values should have their fields removed

OpenAPI, which is in common use, doesn't support null field values (it does
allow omitting that field completely if it is not marked as required).
However that doesn't prevent clients and servers sending and receiving those
fields with null values. Also, in some cases null may be a meaningful value
- for example, JSON Merge Patch {RFC-7396}[RFC 7396]) using null to indicate
property deletion.


[#124]
== {MUST} Empty array values must not be null

Empty array values must either be represented as the empty list, i.e. `[]`, or removed,
which is preferable.


[#125]
== {MUST} Enumerations must be represented as Strings

Strings are a reasonable target for values that are by design enumerations.


[#126]
== {MUST} Date and time property values must conform to RFC 3339

For representation of date and/or time use only the following formats defined
by {RFC-3339}#section-5.6[RFC 3339]:

* for "date" use strings matching RFC `full-date` format, example: `2015-05-28`.
* for "time" use strings matching RFC `partial-time` format, example `14:07:17`.
* for "date and time" use strings matching RFC `date-time` format with only UTC zone offset, example `2015-05-28T14:07:17Z`.

From experience we have learned that zone offsets are not easy to understand
and often not correctly handled, that's why we stick to UTC.
Note also that zone offsets are different from local times that might be
including daylight saving time. Localization of dates should be done by
the services that provide user interfaces, if required.

When it comes to storage, all dates should be consistently stored in UTC
without a zone offset. Localization should be done locally by the
services that provide user interfaces, if required.

Sometimes it can seem data is naturally represented using numerical
timestamps, but this can introduce interpretation issues with precision
- for example whether to represent a timestamp as 1460062925,
1460062925000 or 1460062925.000. Date strings, though more verbose and
requiring more effort to parse, avoid this ambiguity.

Note that the
{OpenAPI-3-0-2}#data-types[OpenAPI format] "date-time" corresponds to "date-time" in the RFC) and
`2015-05-28` for a date (note that the OpenAPI format "date" corresponds
to "full-date" in the RFC). Both are specific profiles, a subset of the
international standard {ISO-8601}[ISO 8601].

[#127]
== {MAY} Time durations and intervals could conform to ISO 8601

Schema based JSON properties that are by design durations and intervals
could be strings formatted as recommended by {ISO-8601}[ISO 8601]
({RFC-3339}#appendix-A[Appendix A of RFC 3339 contains a grammar] for
durations).


[#128]
== {MAY} Standards could be used for Language, Country and Currency

* {ISO-3166-1-a2}[ISO 3166-1-alpha2 country]
* (It's "GB", not "UK")
* {ISO-639-1}[ISO 639-1 language code]
* https://tools.ietf.org/html/bcp47[BCP-47] (based on {ISO-639-1}[ISO 639-1])
  for language variants
* {ISO-4217}[ISO 4217 currency codes]
