[[api-naming]]
= API Naming

[#129]
== {MUST} Use lowercase separate words with hyphens for Path Segments

Example:

[source,http]
----
/shipment-orders/{shipment-order-id}
----

This applies to concrete path segments and not the names of path
parameters. For example `{shipment_order_id}` would be ok as a path
parameter.

[#130]
== {MUST} Use snake_case (never camelCase) for Query Parameters

Examples:

[source]
----
customer_number, order_id, billing_address
----

[#132]
== {SHOULD} Prefer Hyphenated-Pascal-Case for HTTP header Fields

This is for consistency in your documentation (most other headers follow
this convention). Avoid camelCase (without hyphens). Exceptions are
common abbreviations like "ID."

Examples:

[source,http]
----
Accept-Encoding
Apply-To-Redirect-Ref
Disposition-Notification-Options
Original-Message-ID
----

See also: {RFC-7230}#page-22[HTTP Headers are case-insensitive (RFC 7230)].

See <<common-headers>> and <<proprietary-headers>> sections for more guidance
on HTTP headers.

[#134]
== {MUST} Pluralize Resource Names

Usually, a collection of resource instances is provided (at least API
should be ready here). The special case of a resource singleton is a
collection with cardinality 1.

[#135]
== {SHOULD} Not Use /api as Base Path

In most cases, all resources provided by a service are part of the
public API, and therefore should be made available under the root "/"
base path.

If the service should also support non-public, internal APIs
— for specific operational support functions, for example — we encourage 
you to maintain two different API specifications and provide
<<219, API audience>>. For both APIs, you should not use `/api` as base path.

We see API's base path as a part of deployment variant configuration.
Therefore, this information has to be declared in the
{OpenAPI-3-0-2}#server-object[server object].

[#136]
== {MUST} Avoid Trailing Slashes

The trailing slash must not have specific semantics. Resource paths must
deliver the same results whether they have the trailing slash or not.

[#137]
== {MUST} Stick to Conventional Query Parameters

If you provide query support for searching, sorting, filtering, and
paginating, you must stick to the following naming conventions:

* `q` — default query parameter (e.g. used by browser tab completion); should
  have an entity specific alias, like sku
* `sort` — comma-separated (as defined in <<154>>) list of fields to define
  the sort order. To indicate sorting direction, fields may be prefixed with
  `+` (ascending) or `-` (descending), e.g. /sales-orders?sort=+id
* `fields` — to retrieve only a subset of fields of a resource. See <<157>>
  below.
* `embed` — to expand or embedded sub-entities (ie.: inside of an article
  entity, expand silhouette code into the silhouette object). Implementing
  `embed` correctly is difficult, so do it with care. See <<158>> below.
* `offset` — numeric offset of the first element on a page. See <<pagination>>
  section below.
* `cursor` — an opaque pointer to a page, never to be inspected/constructed by
  clients. It usually (encrypted) encodes the identifier of the first or last
  page element, the pagination direction, and the applied query filters to
  recreate the collection. See <<pagination>> section below.
* `limit` — client suggested limit to restrict the number of entries on
  a page. See <<pagination>> section below.

[#X001]
== {SHOULD} Resort to More Advanced Filtering If Needed

Sometimes the default query parameter `q` mentioned in <<137>> isn't enough to
fulfill business or technical requirements around filtering. In such cases
assess if query-by-example using query parameters or OData's `$filter` system
query option doesn't meet the requirements, in that order.

=== Query-by-Example Using Query Parameters

Use a query parameter for each field that should support filtering. Most of the
fields probably do not provide such support. Therefore, document which fields
are filterable.

Given an example listing of the following format:

```json
{
  "items": [
    {
      "id": "1",
      "name": "Infinitec Solutions GMBH",
      "address": {
        "street": "Hardenbergstraße 32",
        "zipCode": "10623",
        "city": "Berlin",
        "country": "Germany"
      }
    }
  ]
}
```

follow these rules to name the query parameters:

* refer directly to collection items (`name`, not `items.name`),
* use "." (dot) to indicate a (unique) field name in nested structure
  (`address.city`, not just `city`).

To support ranges in filtering use virtual fields with suffixes:

* `.gt` - greater than,
* `.lt` - less than,
* `.gte` - greater or equal,
* `.lte` - less or equal.

For example, to allow filtering on `rate` field using ranges (both ends
inclusive), introduce `rate.gte` and `rate.lte` query parameters.

=== OData `$filter` System Query Option

For more complex queries use the https://www.odata.org/[OData]'s http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_SystemQueryOptionfilter[`$filter` system query option]
allowing the client to restrict the set of items returned.

Document which subset of fields, OData's built-in filter operations & built-in
query functions is supported by the endpoint.

////
Comments:
Wilerson: OK
Andrzej: OK
Tugce: OK
////
