[[proprietary-headers]]
= Proprietary Headers

This section shares definitions of proprietary headers that should be
named consistently because they address overarching service-related
concerns. Whether services support these concerns or not is optional;
therefore, the OpenAPI API specification is the right place to make this
explicitly visible. Use the parameter definitions of the resource HTTP
methods.

[#183]
== {MUST} Use Only the Specified Proprietary Headers

As a general rule, proprietary HTTP headers should be avoided. Still,
they can be useful in cases where context needs to be passed through
multiple services in an end-to-end fashion. As such, a valid use-case
for a proprietary header is providing context information, which is not
a part of the actual API, but is needed by subsequent communication.

From a conceptual point of view, the semantics and intent of an
operation should always be expressed by URL's path and query parameters,
the method, and the content. Headers are more often used to implement
functions close to protocol considerations, such as flow control,
content negotiation, and authentication. Thus, headers are reserved for
general context information ({RFC-7231}#section-5[RFC 7231]).

`X-` headers were initially reserved for unstandardized parameters, but the
usage of `X-` headers is deprecated ({RFC-6648}[RFC 6648]). This complicates
the contract definition between consumer and producer of an API following
these guidelines, since there is no aligned way of using those headers.
Because of this, the guidelines restrict which `X-` headers can be used
and how they are used.

The following proprietary headers have been specified by this guideline
for usage so far. Remember that HTTP header field names are not
case-sensitive.

[cols="15%,10%,60%,15%",options="header",]
|=======================================================================
|Header field name |Type |Description |Header field value example

|X-B3-TraceId
|String
|Zipkin tracing: trace identifier. For more information see <<233>>.
|463ac35c9f6413ad

|X-B3-SpanId
|String
|Zipkin tracing: identifier of current span.
|a2fb4a1d1a96d312

|X-B3-ParentSpanId
|String
|Zipkin tracing: identifier of parent span.
|0020000000000001

|X-B3-Sampled
|String
|Zipkin tracing: sampling state.
|1

|X-B3-Flags
|String
|Zipkin tracing: tracing flags.
|1

|X-Api
|String
|API through which the request was initiated. Either `BUSINESS` or `PARTNER`.
|BUSINESS

|X-Actor
|String
|Actor that initiated the request.
|21

|X-AccountId
|String
|Identifier of account in context of which the request is processed.
|17

|X-BusinessId
|String
|Identifier of business in context of which the request is processed.
|30

|X-PartnerUserId
|String
|Identifier of partner user that initiated the request.
|21

|=======================================================================

*Exception:* The only exception to this guideline are the conventional
hop-by-hop `X-RateLimit-` headers which can be used as defined in <<153>>.

[#184]
== {MUST} Propagate Proprietary Headers

All Infinitec's proprietary headers are end-to-end headers.
footnoteref:[header-types, HTTP/1.1 standard ({RFC-7230}#section-6.1[RFC 7230])
defines two types of headers: end-to-end and hop-by-hop headers. End-to-end
headers must be transmitted to the ultimate recipient of a request or response.
Hop-by-hop headers, on the contrary, are meaningful for a single connection
only.]

All headers specified above must be propagated to the services down the call
chain. The header names must remain unchanged. Values of all headers beside
`X-B3-SpanId`, `X-B3-ParentSpanId`, `X-B3-Sampled` and `X-B3-Flags` must remain
unchanged.

Sometimes the value of a proprietary header will be used as part of the entity
in a subsequent request. In such cases, the proprietary headers must still be
propagated as headers with the subsequent request, despite the duplication of
information.

[#233]
== {MUST} Use `X-B3-TraceId`

The *Trace ID* is a generic parameter to be passed through service APIs
and written into log files and traces. A consequent usage of the
*Trace ID* facilitates the tracking of call flows through our system and allows
the correlation of service activities initiated by a specific call. This is
extremely helpful for operational troubleshooting and log analysis. Main use
case of *Trace ID* is to track service calls of our platform and initiated
internal processing flows.

*Service Guidance*

* RESTful API endpoints *must* support `X-B3-TraceId` header in requests.
+
*Note:*  API clients *must* provide _Trace ID_ when calling a service. If no
_Trace ID_ is provided in a request, the service must create a new _Trace ID_.

* Services *must* propagate _Trace ID_, i.e. use _Trace ID_ received
with API calls as:
** input for all APIs called during processing;
** `traceId` data field written for logging and tracing.
